POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQ2YTcxOTFhZWEwMmY4NGZjNjY0ODYiLCJpYXQiOjE2NDE2MjU1NTN9.idW3_TMlLpZfgTr8xkbI-__rTLMizmYAF-BvzqzV4BQ

{
    "title": "C#",
    "description": ".Net",
    "url": "oop",
    "status": "LEARNED"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Create

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "tung30",
    "password": "chip"
}

### Get post data

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQzMTllYmNhNmZiNzNlNDgyM2Y2ZWEiLCJpYXQiOjE2NDEyMjcxOTN9.NLO1VC65FazMJDy-G5hnBQj32b1oGOFe7BiWvGwpZjs

### GPUT

PUT http://localhost:5000/api/posts/61d31a10ca6fb73e4823f6ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQzMTA5MjBhMmU4YTU3MWI1YWQ0YWMiLCJpYXQiOjE2NDEyMjcyOTJ9.GavYe9Y12mz21g0T65evZ7HDWo_Z7qd1g34yJsohbBs

{
    "title": "C==",
    "description": "Thanwg nay ngu",
    "url":"vue",
    "status": "LEARNING"
}

### delete post
DELETE http://localhost:5000/api/posts/61d32af60098cd5382fe6632
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWQzMTllYmNhNmZiNzNlNDgyM2Y2ZWEiLCJpYXQiOjE2NDEyMjcxOTN9.NLO1VC65FazMJDy-G5hnBQj32b1oGOFe7BiWvGwpZjs

{
    "title": "C==",
    "description": "Thanwg nay ngu",
    "url":"vue",
    "status": "LEARNING"
}